### ISSUE TITLE
Emails

### ISSUE THREAD

**Issue by d135-1r43** [thiws24/equipli#104]
# User Story

**Als ausleihender User** möchte ich **eine E-Mail-Bestätigung für meine Reservierung und eine weitere für die erfolgreiche Ausleihe erhalten**, damit ich sicher sein kann, dass meine Transaktionen erfolgreich abgeschlossen wurden.

## Akzeptanzkriterien

1. **Corporate Design**  
   - Die E-Mail folgt dem Corporate Design des Projektes, inklusive Logos, Farben und Schriftarten.  
   - Klare und professionelle Struktur der E-Mail mit personalisiertem Inhalt.  

2. **Versand über separaten Service**  
   - Die E-Mails werden von einem dedizierten E-Mail-Service verschickt, unabhängig von der Hauptapplikation, um Zuverlässigkeit und Skalierbarkeit zu gewährleisten.  

3. **Trigger durch Process Engine**  
   - Die E-Mails werden automatisch durch die Processengine Spiff aus dem BPMN heraus getriggert.

**Comment by Ainges** [comment]
Folgende E-Mails werden für nächsten Dienstag benötigt:

- Reservierungsbestätigung  
- Erfolgreiche Bestätigung durch Lagerwart
- (Stornierungsbestätigung)

Alle E-Mails werden über einen eigenen Endpoint bereitgestellt und erhalten die gleichen Daten, wie [im letzten Kommentar](https://github.com/thiws24/equipli/issues/104#issuecomment-2515022207) beschrieben.

**Comment by Ainges** [comment]
+ Verwendung einer Queue wäre nice

**Comment by Ainges** [comment]
E-Mails funktionieren:
![Image](https://github.com/user-attachments/assets/ecf05c55-d913-45d0-9ebe-3ad9e7640614)
![Image](https://github.com/user-attachments/assets/bbb6e83e-4937-48dd-a936-058b12f0fd89)
![Image](https://github.com/user-attachments/assets/4d74d818-1e7b-4a9e-9ad7-49031e9cfec6)

**Comment by Ainges** [comment]
natürlich funktionieren auch andere Items, wenn man nicht gerade 2 Volleybälle auswählt...


![Image](https://github.com/user-attachments/assets/1db2afa2-ad26-4861-ba14-23e702f8bc29)
