### ISSUE TITLE
deployment Service

### ISSUE THREAD

**Issue by Leo-uni-0305** [thiws24/equipli#108]

**Comment by Ainges** [comment]
Erkenntnis durch aktivierung des erweiterten Loggings:
![Image](https://github.com/user-attachments/assets/6a209aa9-805b-4cd3-a948-f86a6412b956)
Aller Konfiguration zu trotz callt der keycloak client den falschen realm.
Ich werden als nächstes probieren den Client anders als so:

        Keycloak keycloak = Keycloak.getInstance(
                keycloakServerUrl,       // Server URL
                keycloakRealm,           // Realm
                keycloakUsername,        // Username (null für client_credentials)
                keycloakPassword,        // Password (null für client_credentials)
                keycloakClientId,        // Client ID
                keycloakClientSecret     // Client Secret
        );
zu initialisieren...

**Comment by Ainges** [comment]
quarkus war als realm tatsächlich noch an einer anderen Stelle hardcondiert...
Nun laufen wir nur noch auf den resend Fehler...

**Comment by Ainges** [comment]
done✅
