### ISSUE TITLE
Email relay

### ISSUE THREAD

**Issue by Leo-uni-0305** [thiws24/equipli#109]

**Comment by d135-1r43** [comment]
Ich hab mal bei Maileroo einen Account gemacht. Wird gerade verifiziert.

**Comment by Ainges** [comment]
Wie am letzten Dienstag besprochen, hat das leider auch nicht funktioniert. 

Als workaround habe ich einen Gmail Account `info.euipli@gmail.com` erstellt den wir bis auf weiteres für den Mailversand verwenden können.
