### ISSUE TITLE
🚀 ActiveMQ deployen

### ISSUE THREAD

**Issue by Ainges** [thiws24/equipli#144]
Am Dienstag ist im Gespräch mit @nadri23 @baurohnehof @RalfMengele & @zom5583 aufgekommen, dass es schick wäre, wenn der E-Mailversand durch eine Queue entkoppelt wäre.

**Comment by Ainges** [comment]
Einfachheitshalber habe ich einen ActiveMQ classic deployed, da dieser aus der Vorlesung bekannt ist und aus dem Prozess einfach angesprochen werden kann. Die Herausforderung war, dass das [originale Image](https://hub.docker.com/layers/apache/activemq-classic/5.18.5/) keinen Standard User über env Variablen anlegen kann. 
Das wäre allerdings sehr wünschenswert, wenn wird das UI im Web exposen wollen.
Aus diesem Grund wurde ein custom Image in 358dc7aa635fb12e68d0e737eaec969cabe6699c erstellt und in die ghcr des Repos geladen.

**Comment by d135-1r43** [comment]
Puh, ihr seid ja mutig… ;)

**Comment by Ainges** [comment]
@d135-1r43 warum? ^^
