### ISSUE TITLE
Notification per Email  als Erinnerung

### ISSUE THREAD

**Issue by d135-1r43** [thiws24/equipli#47]
Als Nutzer und Lagerwart möchte ich zwei Tage vor Beginn einer Reservierung eine **Abholungserinnerung** per E-Mail erhalten und zwei Tage vor Ende einer Ausleihe eine **Rückgabeerinnerung**, um sicherzustellen, dass alle Prozesse reibungslos ablaufen.

# Akzeptanzkriterien

- **Corporate Identity:**
  - Die E-Mails sind vollständig im Corporate Design der Marke gestaltet, inklusive Logos, Farbpalette und Schriftarten.
- **E-Mail-Versand:**
  - Die E-Mails werden über einen externen SMTP-Server einer SaaS-Lösung versendet, der zuverlässig ist und nicht als Spam eingestuft wird.
- **Automatisierte Timer:**
  - Der Versand der Erinnerungs-E-Mails wird durch Timer ausgelöst, die im BPMN-Prozess definiert und getriggert sind.

**Comment by Ainges** [comment]
@d135-1r43 es sind glaub ich weitere Schritte notwendig bei resend, um einen E-Mail versand zu ermöglichen:
![Image](https://github.com/user-attachments/assets/fe394469-ce56-4731-a8db-569bb1b9c9c3)
Ich versuche als Absender info@equipli.de zu verwenden.

**Comment by Ainges** [comment]
Der Service ist nun auch in Portainer deployed. 
Sobald:

> [@d135-1r43](https://github.com/d135-1r43) es sind glaub ich weitere Schritte notwendig bei resend, um einen E-Mail versand zu ermöglichen: ![Image](https://github.com/user-attachments/assets/fe394469-ce56-4731-a8db-569bb1b9c9c3) Ich versuche als Absender [info@equipli.de](mailto:info@equipli.de) zu verwenden.

gelöst ist, sollte er durch die Prozesse verwendbar sein:
![Image](https://github.com/user-attachments/assets/a754e6d1-f30e-42a6-9675-32b510c42444)
->
![Image](https://github.com/user-attachments/assets/c8b315ed-0d37-4893-bec0-937edf3872f1)

**Comment by Ainges** [comment]
Aktuell erwartet der E-Mail Service folgende Daten: 

Zu klären, ob der Prozess die Daten liefern kann und ob all diese Daten verwendet werden sollen...
```
{
  "to": "string",
  "item": "string",
  "collectionDate": "string",
  "returnDate": "string",
  "pickupLocation": "string",
  "returnLocation": "string"
}
```

**Comment by Ainges** [comment]
Aktuell benötigte Daten pro E-Mail Variante siehe geupdatete README.md
