### ISSUE TITLE
Benutzerverwaltung

### ISSUE THREAD

**Issue by RalfMengele** [thiws24/equipli#52]
### Done
- Einbindung von Keycloak zur Benutzerverwaltung

### To do
- Aktivierung der User-Registration
- Erstellung einer Registration-Page
- Design der Login-Page 
- Branding der beiden Pages anpassen

### optional
- Basic Rollen erstellen (Nutzer, Lagerwart, Dev)

**Comment by HeiligeMeier** [comment]
Funktionalität und Design/Branding sind erledigt und funktionieren.

**Comment by d135-1r43** [comment]
Bitte noch resilient deployen, z. Bsp. über gemountete Volumes im docker-compose Stack.

**Comment by HeiligeMeier** [comment]
User und Rolle sind erstellt und das custom theme wurde im Volume gemountet. 
Könntet ihr das Ticket und das Parent-Ticket #44 gleich schließen? @d135-1r43 @zom5583 

![Image](https://github.com/user-attachments/assets/75f10ab9-bd70-4508-ad93-2deefe3423a0)

**Comment by zom5583** [comment]
Hi , ja mache ich 🤗danke dir

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: HeiligeMeier ***@***.***>
Gesendet: Monday, November 25, 2024 4:49:52 PM
An: thiws24/equipli ***@***.***>
Cc: zom5583 ***@***.***>; Mention ***@***.***>
Betreff: Re: [thiws24/equipli] Benutzerverwaltung (Issue #52)


User und Rolle sind erstellt und das custom theme wurde im Volume gemountet.
Könntet ihr das Ticket und das Parent-Ticket #44<https://github.com/thiws24/equipli/issues/44> gleich schließen? @d135-1r43<https://github.com/d135-1r43> @zom5583<https://github.com/zom5583>

image.png (view on web)<https://github.com/user-attachments/assets/75f10ab9-bd70-4508-ad93-2deefe3423a0>
